---
title: "Normality Assumption"
execute:
  echo: false
format: html
---

## Learning Objective

- Explain the normality assumption of multiple linear regression.
- Explain the consequences of violations of the normality assumption
of multiple linear regression.
- Evaluate the validity of the homoscedasticity assumption of multiple linear regression
in a data set.


## Lesson

### Assumption

We can write this assumption in a couple ways.
The first is
$$
Y_i = \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \cdots + \beta_p X_{ip} + \epsilon_i
$$
and $\epsilon_i|X_{i1},\dotsc,X_{ip}$ is normally distributed.
In words, we're assuming that the random error that gets added to
our linear function is normally distributed.
The second is that $Y_i|X_{i1},\dotsc,X_{ip}$ is normally distributed.

### Consequences

If this assumption is not met, and you have a small sample size,
the p-values that R outputs are not trustworthy.
If this assumption is not met, but you have a large sample size
and the linearity, iid, and homoscedasticity assumptions are met,
you can still trust the default p-values in R output.

How large of a sample is large enough?
This depends on how many covariates are in your model (how large $p$ is)
and how asymmetric your residuals are.
It's hard to give a single rule,
so when in doubt, consult a statistician.

### Evaluation

The way we check this assumption is exactly the same as for simple linear
regression:
we check if the residuals are normal.
I like to use a boxplot, histogram, and q-q plot to check this.



## Problems

### Problem 1

The following plots are of residuals from a regression of heart rate
(in beats per minute)
on age (in years), sex (male or female), admission type (elective or emergency),
and consciousness (conscious, deep stupor, or coma).
The participants were 200 patients admitted to an adult
intensive care unit (ICU).

```{r}
d <- Lock5Data::ICUAdmissions
# sum(complete.cases(d))
d$sex <- "Male"
d$sex[d$Sex == 1] <- "Female"
d$type <- "Elective"
d$type[d$Type == 1] <- "Emergency"
d$consciousness <- "Conscious"
d$consciousness[d$Consciousness == 1] <- "Deep Stupor"
d$consciousness[d$Consciousness == 2] <- "Coma"
mod_01 <- lm(formula = HeartRate ~ Age + sex + type + consciousness,
             data = d)
boxplot(x = mod_01$residuals,
        ylab = "Residuals")
hist(x = mod_01$residuals,
     xlab = "Residuals")
qqnorm(mod_01$residuals)
qqline(mod_01$residuals)
```

Does this model satisfy the normality assumption?

::: {.callout-tip title="Solution" collapse="true"}

Yes. From the boxplot, we see the residuals are symmetric;
the histogram shows the residuals have a bell shape
(with maybe a slight right skew);
and in the q-q plot the points mostly follow the reference line.
So, the residuals are normal,
which is evidence that the random errors are normal.

:::






