---
title: "Confounders and Mediators"
execute:
  echo: false
format: html
---

## Learning Objective

Define, use, and interpret the terms "confounder" and "mediator".


## Lesson

### Counfounder

Sometimes, we think one thing causes another.
For example, we might see that people who take a certain drug
often die soon after,
so we think the drug causes the death.

```{mermaid}
flowchart LR
  A[Drug] --> B[Death]
```

Sometimes, a third thing causes both of the original events.
In the drug/death example,
it may be the case that only very sick people take the drug,
so it's the underlying illness that leads people to take the drug
and to die soon after,
and the drug does not increase risk of death.

```{mermaid}
flowchart LR
  C[Illness] --> A[Drug]
  C --> B[Death]
```

This third thing, which causes (or is at least associated with)
the two original things, is called a confounder.

### Mediator

Sometimes, one thing causes a second thing, which causes a third thing.
We call the second thing a mediator.
For example, you might take
[calcium carbonate](https://my.clevelandclinic.org/health/drugs/20402-calcium-carbonate-chewable-tablets),
which reduces the amount of acid in the stomach,
which reduces
[heartburn](https://my.clevelandclinic.org/health/diseases/9617-heartburn-overview).

```{mermaid}
flowchart LR
  A[Calcium carbonate] --> B[Reduced Acid]
  B --> C[Reduced Heartburn]
```

In this example, the reduced acid is a mediator.

### Regression

What does this have to do with regression?

#### Confounding

Suppose you are studying child health in a developing country.
For one analysis, you use weight as the outcome,
since it can be a proxy for child health in poor environments.
In a simple linear regression,
you use a binary variable as the explanatory variable,
where the two levels are public school and private school.
You find that, on average, private school students weigh more than
public school students, and the difference is statistically significant.

A colleague asks,
"What is it about private school that makes students healthier?
Are they learning about nutrition?"
On a hunch, you decide to add an additional explanatory variable to the model.
In your data set, you also measured how much each child's family spends on food.
You add that to the model
and the coefficient for school is no longer statistically significant.

This is evidence that family wealth is a confounder.
Wealthier families can afford to send their kids to private school
and to spend more on food.

I have to add a caveat here,
which is that although this is evidence that family wealth is a confounder,
evidence is not the same as proof.
With each new covariate added to the model,
you decrease the power to detect non-zero coefficients.
So, although regression can be a tool in causal inference,
it is far from perfect.


#### Mediation

Suppose that in the next phase of your research,
you conduct a randomized controlled trial where you randomly assign
some students to receive free food.

## Problems

### Problem 1



::: {.callout-tip title="Solution" collapse="true"}



:::

### Problem 2



::: {.callout-tip title="Solution" collapse="true"}



:::




