---
title: "Interaction Between One Binary Variable and One Categorical Variable"
execute:
  echo: false
format: html
---

## Learning Objective

Interpret the coefficients of a multiple linear regression model with an
interaction between one binary variable and one categorical variable.


## Lesson



Jeremy Groves, an anesthetist in the UK,
timed his commute when using two different bikes.
Below are the results of a regression of commute time in minutes
on bike type (steel or carbon) and month of the year (January through July),
with an interaction between the two explanatory variables.
The distance traveled was approximately 27 miles for each commute.
```{r}
d2 <- Lock5Data::BikeCommute
mod_03 <- lm(formula = Minutes ~ Bike * Month,
             data = d2)
summary(mod_03)
```

How do we interpret these coefficients?
We can represent the model as follows
(please forgive the abbreviations):
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste},\texttt{Feb},\texttt{Mar},\texttt{Apr},\texttt{May},\texttt{Jun},\texttt{Jul}\right) \\
&= 114.755 + 0.655 \texttt{Ste} + 3.588 \texttt{Feb} - 3.662\texttt{Mar} - 11.698\texttt{Apr} - 10.215 \texttt{May} - 14.375 \texttt{Jun} -9.655 \texttt{Jul} \\
&\qquad - 5.972 \texttt{Ste}\times\texttt{Feb} - 3.465 \texttt{Ste}\times\texttt{Mar} + 5.622 \texttt{Ste}\times\texttt{Apr} - 2.473 \texttt{Ste}\times\texttt{May} + 3.567 \texttt{Ste}\times\texttt{Jun} + 0.947 \texttt{Ste}\times\texttt{Jul} \text{.}
\end{align*}
$$



### Intercept

The estimated mean commute time in January on a carbon bike is 114.755 minutes.
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=0,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul=0}\right) \\
&= 114.755 + 0.655 (0) + 3.588 (0) - 3.662(0) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (0)\times(0) - 3.465 (0)\times(0) + 5.622 (0)\times(0) - 2.473 (0)\times(0) + 3.567 (0)\times(0) + 0.947 (0)\times(0) \\
&= 114.755 \text{.}
\end{align*}
$$


### Comparing Months on a Carbon Bike

The estimated mean difference in commute times between January and February
on a carbon bike is 3.588 minutes, with February taking longer.
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=1,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&\qquad - \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=0,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&= 114.755 + 0.655 (0) + 3.588 (1) - 3.662(0) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (0)\times(1) - 3.465 (0)\times(0) + 5.622 (0)\times(0) - 2.473 (0)\times(0) + 3.567 (0)\times(0) + 0.947 (0)\times(0) \\
&\qquad - 114.755 \\
&= 3.588 \text{.}
\end{align*}
$$

The estimated mean difference in commute times between January and March
on a carbon bike is 3.662 minutes, with January taking longer.
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=0,\texttt{Mar}=1,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&\qquad - \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=0,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&= 114.755 + 0.655 (0) + 3.588 (0) - 3.662(1) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (0)\times(0) - 3.465 (0)\times(1) + 5.622 (0)\times(0) - 2.473 (0)\times(0) + 3.567 (0)\times(0) + 0.947 (0)\times(0) \\
&\qquad - 114.755 \\
&= -3.662 \text{.}
\end{align*}
$$

I hope this demonstrates a pattern:
The coefficients on each month variable represent a comparison between
that month and January,
on a carbon bike.

- The estimated mean difference in commute times between January and April
on a carbon bike is 11.698 minutes, with January taking longer.
- The estimated mean difference in commute times between January and May
on a carbon bike is 10.215 minutes, with January taking longer.
- The estimated mean difference in commute times between January and June
on a carbon bike is 14.375 minutes, with January taking longer.
- The estimated mean difference in commute times between January and July
on a carbon bike is 9.655 minutes, with January taking longer.

### Comparing Months on a Steel Bike

The estimated mean difference in commute times between January and February
on a steel bike is $|3.588-5.972| = |-2.384| = 2.384$ minutes,
with January taking longer:
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=1,\texttt{Feb}=1,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&\qquad - \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=1,\texttt{Feb}=0,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&= 114.755 + 0.655 (1) + 3.588 (1) - 3.662(0) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (1)\times(1) - 3.465 (1)\times(0) + 5.622 (1)\times(0) - 2.473 (1)\times(0) + 3.567 (1)\times(0) + 0.947 (1)\times(0) \\
&\qquad - (114.755 + 0.655 (1) + 3.588 (0) - 3.662(0) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (1)\times(0) - 3.465 (1)\times(0) + 5.622 (1)\times(0) - 2.473 (1)\times(0) + 3.567 (1)\times(0) + 0.947 (1)\times(0)) \\
&= 114.755 + 0.655 + 3.588 - 5.972 - (114.755 + 0.655) \\
&= 3.588 -5.972 \\
&= -2.384 \text{.}
\end{align*}
$$

The estimated mean difference in commute times between January and March
on a steel bike is $|-3.662-3.465| = |-7.127| = 7.127$ minutes,
with January taking longer:
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=1,\texttt{Feb}=0,\texttt{Mar}=1,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&\qquad - \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=1,\texttt{Feb}=0,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&= 114.755 + 0.655 (1) + 3.588 (0) - 3.662(1) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (1)\times(0) - 3.465 (1)\times(1) + 5.622 (1)\times(0) - 2.473 (1)\times(0) + 3.567 (1)\times(0) + 0.947 (1)\times(0) \\
&\qquad - (114.755 + 0.655) \\
&= 114.755 + 0.655 - 3.662 - 3.465 - (114.755 + 0.655) \\
&= -3.662 - 3.465 \\
&= -7.127 \text{.}
\end{align*}
$$

If we want to compare a month to January on a steel bike,
we must combine the coefficient on that month with the coefficient
on the interaction term between that month and steel.

- The estimated mean difference in commute times between January and April
on a steel bike is $|-11.698 + 5.622| = |-6.076| = 6.076$ minutes,
with January taking longer.
- The estimated mean difference in commute times between January and May
on a steel bike is $|-10.215-2.473| = |-12.688| = 112.688$ minutes,
with January taking longer.
- The estimated mean difference in commute times between January and June
on a steel bike is $|-14.375+3.567| = |-10.808| = 10.808$ minutes,
with January taking longer.
- The estimated mean difference in commute times between January and July
on a steel bike is $|-9.655+0.947| = |-8.708| = 8.708$ minutes,
with January taking longer.

### Comparing Carbon to Steel by Month

The estimated mean difference in commute times between carbon and steel
bikes during the month of January is 0.655 minute,
with the steel taking longer:
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=1,\texttt{Feb}=0,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&\qquad - \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=0,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&= 114.755 + 0.655 (1) + 3.588 (0) - 3.662(0) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (1)\times(0) - 3.465 (1)\times(0) + 5.622 (1)\times(0) - 2.473 (1)\times(0) + 3.567 (1)\times(0) + 0.947 (1)\times(0) \\
&\qquad - 114.755 \\
&= 0.655 \text{.}
\end{align*}
$$

The estimated mean difference in commute times between carbon and steel
bikes during the month of February is
$|0.655-5.972| = |-5.317| = 5.317$ minutes,
with the carbon taking longer:
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=1,\texttt{Feb}=1,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&\qquad - \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=1,\texttt{Mar}=0,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&= 114.755 + 0.655 (1) + 3.588 (1) - 3.662(0) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (1)\times(1) - 3.465 (1)\times(0) + 5.622 (1)\times(0) - 2.473 (1)\times(0) + 3.567 (1)\times(0) + 0.947 (1)\times(0) \\
&\qquad - (114.755 + 0.655 (0) + 3.588 (1) - 3.662(0) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (0)\times(1) - 3.465 (0)\times(0) + 5.622 (0)\times(0) - 2.473 (0)\times(0) + 3.567 (0)\times(0) + 0.947 (0)\times(0)) \\
&= 114.755 + 0.655 + 3.588 - 5.972 - (114.755 + 3.588) \\
&= 0.655 - 5.972 \\
&= -5.317 \text{.}
\end{align*}
$$

The estimated mean difference in commute times between carbon and steel
bikes during the month of March is
$|0.655-3.465| = |-2.81| = 2.81$ minutes,
with the carbon taking longer:
$$
\begin{align*}
& \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=1,\texttt{Feb}=0,\texttt{Mar}=1,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&\qquad - \hat{E}\left(\texttt{Min}\middle|\texttt{Ste}=0,\texttt{Feb}=0,\texttt{Mar}=1,\texttt{Apr}=0,\texttt{May}=0,\texttt{Jun}=0,\texttt{Jul}=0\right) \\
&= 114.755 + 0.655 (1) + 3.588 (0) - 3.662(1) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (1)\times(0) - 3.465 (1)\times(1) + 5.622 (1)\times(0) - 2.473 (1)\times(0) + 3.567 (1)\times(0) + 0.947 (1)\times(0) \\
&\qquad - (114.755 + 0.655 (0) + 3.588 (0) - 3.662(1) - 11.698(0) - 10.215 (0) - 14.375 (0) -9.655 (0) \\
&\qquad - 5.972 (0)\times(0) - 3.465 (0)\times(1) + 5.622 (0)\times(0) - 2.473 (0)\times(0) + 3.567 (0)\times(0) + 0.947 (0)\times(0)) \\
&= 114.755 + 0.655 - 3.662 - 3.465 - (114.755 - 3.662) \\
&= 0.655 - 3.465 \\
&= -2.81 \text{.}
\end{align*}
$$

I hope this demonstrates a pattern:
If we want to compare carbon to steel in January,
we just need the coefficient on steel.
If we want to compare carbon to steel in another month,
we have to combine the coefficient on steel with the coefficient
on the interaction term between that month and steel.

- The estimated mean difference in commute times between carbon and steel
bikes during the month of April is
$|0.655+ 5.622| = |6.277| = 6.277$ minutes,
with the steel taking longer.
- The estimated mean difference in commute times between carbon and steel
bikes during the month of May is
$|0.655-2.473| = |-1.818| = 1.818$ minutes,
with the carbon taking longer.
- The estimated mean difference in commute times between carbon and steel
bikes during the month of June is
$|0.655+3.567| = |4.222| = 4.222$ minutes,
with the steel taking longer.
- The estimated mean difference in commute times between carbon and steel
bikes during the month of July is
$|0.655+0.947| = |1.602| = 1.602$ minutes,
with the steel taking longer.





## Problems

### Problem 1

Is there evidence of moderation between month, bike type,
and commute time?
Justify your answer.

::: {.callout-tip title="Solution" collapse="true"}

Since none of the interaction term coefficients have p-values below 0.05,
any moderation we're seeing is not more than would be expected by chance
alone.
So, no, there isn't evidence of moderation.
I would refit the model without the interaction terms.

:::






