---
title: "Parameter and Statistic"
execute:
  echo: false
format: html
---

## Learning Objectives

- Compare and contrast the terms "parameter" and "statistic".
- Determine whether a quantity is a parameter or statistic.


## Lesson

A parameter is a function of a population.
For example, the expected value is a parameter.
A statistic is a function of a sample.
For example, the sample average is a statistic.

Unfortunately, it is often the case that the same word could be a parameter
or statistic depending on context.
Consider the median.
Every population distribution has a median.
For a continuous random variable,
the area under the curve to the right of the median is 0.5.
(The definition of the median for a discrete random variable
is more complicated,
so I'm just going to avoid it for now.)

Every sample has a median, too.
To get the sample median, you line up all the values in the sample
from smallest to largest.
If there are $n$ observations, and $n$ is odd,
the median is the $\frac{n+1}{2}$th value in the list.
For example, in the data set $\{0,3,4,5,15\}$,
the median is 4.
If there are $n$ observations, and $n$ is even,
the median is the average of the $\frac{n}{2}$th
and $\left(\frac{n}{2}+1\right)$th values in the list.
For example, in the data set $\{0,3,4,5,15,24\}$,
the median is
$$
\frac{4 + 5}{2} = 4.5 \text{.}
$$




## Problems

### Problem 1

Is the maximum value in my sample a parameter or a statistic?

::: {.callout-tip title="Solution" collapse="true"}

It's a statistic, because it's something you computed from your data.

:::

### Problem 2

In clinical trials, we often want to know the expected difference
in some outcome (e.g., blood pressure, risk of death)
between people who take a drug and people who don't
Is this a parameter or a statistic?

::: {.callout-tip title="Solution" collapse="true"}

This is a parameter.
If we randomly assign some people to receive a drug and some people to
receive a placebo,
and then compute the difference between the averages of the outcome
across the groups,
that would be a statistic.

:::

### Problem 3

Suppose $X_1,\dotsc,X_n$ are iid random variables.
Suppose also that $Var(X_1) > 0$.

#### Part (a)

Is $X_1 = X_2$?

::: {.callout-tip title="Solution" collapse="true"}

It's impossible to know ahead of time.
These are random variables, so they could have the same value,
or they could have different values.
We won't know until we collect our data.
Also, if $X_1$ is a continuous random variable,
then $P(X_1 = X_2) = 0$.

:::

#### Part (b)

Is $E(X_1) = E(X_2)$?

::: {.callout-tip title="Solution" collapse="true"}

Yes. Because these random variables have the same distributions,
they must have the same expected values.
The expected value is a parameter of the distribution;
it is fixed.

:::

#### Part (c)

Is $E(X_1) = \frac{1}{n} \sum_{i=1}^n X_i$?

::: {.callout-tip title="Solution" collapse="true"}

It's impossible to know beforehand.
This could happen by chance,
but if $X_1$ is a continuous random variable,
it has probability zero of occurring.

:::

#### Part (d)

Is $E(X_1)$ a parameter, a statistic, both, or neither?

::: {.callout-tip title="Solution" collapse="true"}

Parameter.

:::

#### Part (e)

Is $\frac{1}{n} \sum_{i=1}^n X_i$ a parameter, a statistic, both, or neither?

::: {.callout-tip title="Solution" collapse="true"}

Statistic.

:::

### Problem 4

You are the statistical consultant for doctoral students
in another department.
One of these students interviewed 33 teenage girls
for her dissertation.
She had recruited them from Boston Latin School,
near HSPH.
Of these 33 teenage girls,
22 said they had been bullied.
The doctoral student includes this line in her dissertation:
"Sixty-seven percent of teenage girls have experienced bullying."
What feedback/advice would you give her about this line?

::: {.callout-tip title="Solution" collapse="true"}

Sixty-seven percent of the girls in the sample have experienced bullying,
but that doesn't necessarily imply that sixty-seven percent of
all teenage girls have experienced bullying.
Sixty-seven percent is a statistic computed from the sample,
not the parameter for the population.
Also, the sample may not be representative of the whole population.
Boston Latin School requires applicants to take an exam
in order to qualify for admission,
so its students are very high-achieving.
Finally, 33 observations is a pretty small sample size.
In order to make more reliable claims about the population
of teenage girls,
we should probably collect more data.

:::








