---
title: "Math Refresher"
format: html
---

Doing statistics necessarily requires doing some mathematics,
even if that mathematics is identifying which of two numbers is larger
than the other.
In this section, I've collected those math skills that I think
are most important for understanding the material that follows.

## Equations

Researchers often summarize their regression into a single equation;
it's a compact way to represent the outcome, the covariates,
and how they relate to each other.
Also, interpreting coefficients requires some manipulation
of equations.
So, it's important that we are on the same page about how they work.

An equals sign indicates that the two sides of the equation are exactly
equal to each other:
$$
a = a \text{.}
$$
This implies that if we have an equation, and we do the same exact thing
to both sides, the equality will still be true.
For example,
$$
a + 3 = a + 3 \text{.}
$$
We started from the same place, so if we move the same distance in the same
direction,
we should end up in the same place.

Of course, this applies to other operations besides addition:
$$
\begin{align*}
3a &= 3a \\
a/3 &= a/3 \\
a - 3 &= a - 3 \text{.}
\end{align*}
$$




## Logarithms




## Intercept and Slope



## Problems

### Problem 1

Solve for $a$:
$$
3a + 5 = 17 \text{.}
$$

Solution:
$$
\begin{align*}
3a + 5 &= 17 \\
3a &= 12 \\
a &= 4 \text{.}
\end{align*}
$$


















