---
title: "Poisson Distribution"
execute:
  echo: false
format: html
---

## Learning Objective

- State the following, regarding the Poisson distribution:
  - What the distribution is intended to represent.
  - The support.
  - What the parameter represents.
  - The variance.
  - How to represent the mean in terms of rate and time.


## Lesson

### What's Important to Know

The Poisson distribution is a discrete distribution that forms the basis
of Poisson regression.
If $Y\sim\text{Poisson}(\mu)$,
this is what is important to know:

- $Y$ is a count. More specifically,
$Y$ is a count of the number of events happening in a defined time
and place, where the rate of events is constant.
- Since $Y$ is a count, $Y$ can be any non-negative whole number,
i.e., 0, 1, 2, 3, 4, 5, etc.
There is no upper limit.
- The single parameter, $\mu$, represents the expected value.
So, $\mu = E(Y)$.
- The variance of the Poisson distribution is exactly equal to its mean.
So, $Var(Y) = \mu$.
- The expected value, $\mu$, can also be represented as the product
of the rate, $\lambda$, and the time period over which the counting is occurring.
The duration of this time period is $t$.
So, we can write $\mu = \lambda t$.

### Examples

#### Measles

Suppose $Y_i$ is the number of new cases of measles in the state of
Massachusetts in year $i$.
$Y_i$ is a count,
so we won't see a negative or fractional number.
It might be reasonable to assume that the expected (or mean) number
of measles is the same each year,
i.e., that measles cases in Massachusetts occur at the same, low rate.
We can call the yearly rate $\lambda$, where the units of $\lambda$
are cases per year.
The yearly mean is $\mu = \lambda \times 1 = \lambda$.
If we wanted $Y_i$ to be the number of new cases in month $i$,
then $\mu$ would be $\lambda / 12$.

#### Words

Suppose $Y_i$ is the number of times the word "the" appears on the $i$th
page of a book.
Again, $Y_i$ is a count.
It might be reasonable to assume that the expected number of times
the word "the" appears on a page is the same for each page.
We can call this count per page $\lambda$,
so that $E(Y_i) = \lambda = \mu$.
If we wanted $Y_i$ to be the number of times the word "the" appears
in the $i$th chapter of the book,
we would need to know $t_i$, the number of pages in the $i$th chapter.
Then $\mu_i = \lambda t_i$.
In this example, $t_i$ varies with $i$,
and it's not a time, it's a count of pages.
This is common with the Poisson distribution;
$t$ may not be a literal duration in time,
but may represent some other quantity.

#### Trees

[Tongass National Forest](https://www.fs.usda.gov/r10/tongass/about-area),
at nearly 17 million acres,
is the largest national forest in the US.
Suppose we wanted to estimate the number of spruce trees
in the forest.
We could sample several small sections of the forest
and count the number of spruce trees in each section.
Suppose each section is one acre, and we sample 100 acres.
We could let $Y_i$ be the number of (live) spruce trees in the $i$th section.
Again, this would be a non-negative whole number.
$E(Y_i) = \mu$ would be the expected number of spruce trees in a single acre.

If we wanted to vary the size of our sections,
we could let $t_i$ denote the number of acres in the $i$th section,
and $\lambda$ denote the expected number of spruce trees per acre.
Then $E(Y_i) = \mu_i = \lambda t_i$.
In this example, $t_i$ is not a measure of time,
but of area.

## Problems

### Problem 1

Fill in the rest of this table.

| | Normal Distribution | Bernoulli Distribution | Poisson Distribution |
|:-|:-|:-|:-|
| Support |  |  |  |
| Expected value | $\mu$ |  |  |
| Variance | $\sigma^2$ |  |  |

::: {.callout-tip title="Solution" collapse="true"}

| | Normal Distribution | Bernoulli Distribution | Poisson Distribution |
|:-|:-|:-|:-|
| Support | Any real number | $\{0,1\}$ | $\{0,1,2,3,4,\dotsc\}$ |
| Expected value | $\mu$ | $p$ | $\mu = \lambda t$ |
| Variance | $\sigma^2$ | $p(1-p)$ | $\mu = \lambda t$ |

:::

### Problem 2

Suppose your office sees, on average, $\lambda$
[talon cusps](https://doi.org/10.1136/bcr-2022-252227) per year.
How many talon cusps would you expect to see over ten years?

::: {.callout-tip title="Solution" collapse="true"}

$10\lambda$

:::




